const VOUCHER_TYPE = {
  FIXED_AMOUNT: 'FIXED_AMOUNT',
  PERCENTAGE: 'PERCENTAGE',
};

const VOUCHER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};

export { VOUCHER_TYPE, VOUCHER_STATUS };
